import { Movie } from './model/movie';

export const MOVIES: Movie[] = [
    {title: 'Terminator 2: Judgment Day',
    year: 1991,
    imdbId: 'tt0103064',
    type: 'movie',
    poster: '../assets/terminator2.jpg'},
    {title: 'The Terminator',
    year: 1984,
    imdbId: 'tt0088247',
    type: 'movie',
    poster: '../assets/terminator.jpg'},
    {title: 'Terminator 3: Machines\' Rise',
    year: 2003,
    imdbId: 'tt0181852',
    type: 'movie',
    poster: '../assets/terminator3.jpg'},
    {title: 'Terminator Salvation',
    year: 2009,
    imdbId: 'tt0438488',
    type: 'movie',
    poster: '../assets/terminator-salvation.jpg'},
    {title: 'Terminator Genisys',
    year: 2015,
    imdbId: 'tt1340138',
    type: 'movie',
    poster: '../assets/terminator-genisys.jpg'},
    {title: 'Terminator: Sarah\'s Chronicles',
    year: 2008,
    imdbId: 'tt0851851',
    type: 'series',
    poster: '../assets/sarah-chronicles.jpg'},
    {title: 'Terminator: Dark Fate',
    year: 2019,
    imdbId: 'tt6450804',
    type: 'movie',
    poster: '../assets/dark-fate.jpg'},
    {title: 'Lady Terminator',
    year: 1989,
    imdbId: 'tt0095483',
    type: 'movie',
    poster: '../assets/lady-terminator.jpg'}
]