import { Movie } from './model/movie';

export const MOVIES: Movie[] = [
    {title: 'Terminator 2: Judgment Day',
    year: 1991,
    imdbId: 'tt0103064',
    type: 'movie',
    poster: 'https://m.media-amazon.com/images/M/MV5BMGU2NzRmZjUtOGUxYS00ZjdjLWEwZWItY2NlM2JhNjkxNTFmXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg'},
    {title: 'The Terminator',
    year: 1984,
    imdbId: 'tt0088247',
    type: 'movie',
    poster: 'https://m.media-amazon.com/images/M/MV5BYTViNzMxZjEtZGEwNy00MDNiLWIzNGQtZDY2MjQ1OWViZjFmXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg'},
    {title: 'Terminator 3: Rise of the Machines',
    year: 2003,
    imdbId: 'tt0181852',
    type: 'movie',
    poster: 'https://m.media-amazon.com/images/M/MV5BMTk5NzM1ODgyN15BMl5BanBnXkFtZTcwMzA5MjAzMw@@._V1_SX300.jpg'},
    {title: 'Terminator Salvation',
    year: 2009,
    imdbId: 'tt0438488',
    type: 'movie',
    poster: 'https://m.media-amazon.com/images/M/MV5BODE1MTM1MzA2NF5BMl5BanBnXkFtZTcwODQ5MTA2Mg@@._V1_SX300.jpg'},
    {title: 'Terminator Genisys',
    year: 2015,
    imdbId: 'tt1340138',
    type: 'movie',
    poster: 'https://m.media-amazon.com/images/M/MV5BMjM1NTc0NzE4OF5BMl5BanBnXkFtZTgwNDkyNjQ1NTE@._V1_SX300.jpg'},
    {title: 'Terminator: The Sarah Connor Chronicles',
    year: 2008,
    imdbId: 'tt0851851',
    type: 'series',
    poster: 'https://m.media-amazon.com/images/M/MV5BZGE2ZDgyOWUtNzdiNS00OTI3LTkwZGQtMTMwNzM4YWUxNGNhXkEyXkFqcGdeQXVyNjU2NjA5NjM@._V1_SX300.jpg'},
    {title: 'Terminator: Dark Fate',
    year: 2019,
    imdbId: 'tt6450804',
    type: 'movie',
    poster: 'https://m.media-amazon.com/images/M/MV5BNzhlYjE5MjMtZDJmYy00MGZmLTgwN2MtZGM0NTk2ZTczNmU5XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg'},
    {title: 'Lady Terminator',
    year: 1989,
    imdbId: 'tt0095483',
    type: 'movie',
    poster: 'https://m.media-amazon.com/images/M/MV5BMTg5NTA1NzEtNWNiNy00ZTc4LWJhZTgtYmJkODZhYWI3NmQ4XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg'}
]